server:
  http_listen_port: 3100

auth_enabled: false

common:
  # no 'path' here in 2.9.x
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-15
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /loki/chunks
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/boltdb-cache
    shared_store: filesystem

ingester:
  wal:
    enabled: true
    dir: /loki/wal

query_range:
  parallelise_shardable_queries: true

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_query_lookback: 168h
  ingestion_rate_mb: 8
  ingestion_burst_size_mb: 16

compactor:
  working_directory: /loki/compactor
  compaction_interval: 5m


# server:
#   http_listen_port: 3100
# 
# auth_enabled: false
# 
# common:
#   path: /loki
#   storage:
#     filesystem:
#       chunks_directory: /loki/chunks
#       rules_directory: /loki/rules
#   ring:
#     instance_addr: 127.0.0.1
#     kvstore:
#       store: inmemory
# 
# schema_config:
#   configs:
#     - from: 2020-10-15
#       store: boltdb-shipper
#       object_store: filesystem
#       schema: v13
#       index:
#         prefix: index_
#         period: 24h
# 
# storage_config:
#   filesystem:
#     directory: /loki/chunks
#   boltdb_shipper:
#     active_index_directory: /loki/index
#     cache_location: /loki/boltdb-cache
#     shared_store: filesystem
# 
# query_range:
#   parallelise_shardable_queries: true
# 
# limits_config:
#   reject_old_samples: true
#   reject_old_samples_max_age: 168h
#   max_query_lookback: 168h
#   ingestion_rate_mb: 8
#   ingestion_burst_size_mb: 16
# 
# compactor:
#   working_directory: /loki/compactor
#   compaction_interval: 5m

