server:
  http_listen_port: 9080

positions:
  filename: /run/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets: [localhost]
        labels:
          job: docker-logs
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - docker: {}


# server:
#   http_listen_port: 9080
#   grpc_listen_port: 9095
# 
# clients:
#   - url: http://loki:3100/loki/api/v1/push
# 
# scrape_configs:
#   - job_name: system
#     static_configs:
#       - targets:
#           - localhost
#         labels:
#           job: varlogs
#           __path__: /var/log/*.log
#   - job_name: docker
#     static_configs:
#       - targets:
#           - localhost
#     docker_sd_configs:
#       - host: unix:///var/run/docker.sock
#     relabel_configs:
#       - source_labels: ['__meta_docker_container_name']
#         regex: /(.+)
#         target_label: 'container'
#       - source_labels: ['__meta_docker_container_name']
#         regex: /(.+)
#         target_label: 'instance'
#       - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
#         regex: (.+)
#         target_label: 'service'
# 
# 